
application: intro
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: intro.app

libraries:
- name: jinja2
  version: latest
- name: setuptools
  version: latest